spring.application.name=easedine
spring.datasource.url=jdbc:h2:mem:easedine

# h2 database

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# spring.datasource.username=test
# spring.datasource.password=test


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update